spring.application.name=retailsoftware


spring.datasource.url=jdbc:postgresql://localhost:5432/retail_billing
spring.datasource.username=bipanshu
spring.datasource.password=bipanshu544
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
