spring.application.name=retailsoftware

spring.datasource.url=jdbc:postgresql://ep-shiny-bar-ank6ypnl-pooler.c-6.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_hymn4V3bCAgv
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true